### ISSUE TITLE
zIndex of pixi overlay

### ISSUE THREAD

**Issue by mladenp** [manubb/Leaflet.PixiOverlay#15]
So i am having trouble putting Pixi markers on top of other leaflet layers.
I created new map pane for Pixi overlay and can change zIndex successfully. But when i put 999 zIndex for Pixi pane it doesn't go on top of polylines, event though they have lower zIndex by default.

Note:
I see that regular leaflet layers have pane property inside _options_ property while pixi layer has it root of layer object, and in _options_ property it contains only 'forceCanvas'.

**Comment by manubb** [comment]
Can you try with absolute positioning on leaflet-pixi-overlay container:
```css
.leaflet-pixi-overlay {position:absolute;}
```
?

**Comment by mladenp** [comment]
It didn't help, tried setting pos absolute on 'leaflet-pane' also but no luck.
Is the _pane_ property on the correct place in layer object? It looks it should be inside _options_

**Comment by manubb** [comment]
The `z-index` of the `svg` pane is 200. In my tests, if i set:
 ```css
.leaflet-pixi-overlay {
  position:absolute;
  z-index: 201;
}
```
the pixi overlay is before the `svg`. If i set:
 ```css
.leaflet-pixi-overlay {
  position:absolute;
  z-index: 199;
}
```
the `svg` is before the pixi overlay. 
Are you certain this does not solve your problem? If it is the case, can you give me the versions of the libs you use, your browser name and version and some sample code, possibly in a fiddle?
